language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - sonar-scanner
before_install:
- openssl aes-256-cbc -K $encrypted_ad7a8f916345_key -iv $encrypted_ad7a8f916345_iv
  -in travis-encrypted.tar.enc -out travis-encrypted.tar -d
- tar xvf travis-encrypted.tar
install:
- ". travis-install.sh"
before_script:
- ". travis-before-script.sh"
script:
- ". travis.sh"
after_success:
- ". travis-after-success.sh"
notifications:
  email: false
